# Generated by Django 3.1.7 on 2021-03-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0002_auto_20210317_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='my_portfolio.ProjectTags', verbose_name='Теги'),
        ),
    ]
