# Generated by Django 3.1.7 on 2021-04-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0006_auto_20210408_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AddField(
            model_name='skills',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='Очередность'),
        ),
    ]
